name: Splatoon
main: me.crafter.mc.splatoon.Splatoon
version: 1.0
author: connection_lost
description: >
             Splatoon in Minecraft
commands:
   splatoon:
      permission: splatoon.admin
      usage: |
         /splatoon